const KEY='learning-roadmap-v4',OLD_KEYS=['learning-roadmap-v3','learning-roadmap-v2'];
const DEF={settings:{startDate:'',jpWeekly:240,finWeekly:240,jpSession:45,finSession:60},logs:{},done:{}};
let state=loadState();
function clone(x){return JSON.parse(JSON.stringify(x))}
function loadState(){try{const cur=localStorage.getItem(KEY);if(cur)return normalise(JSON.parse(cur));for(const k of OLD_KEYS){const raw=localStorage.getItem(k);if(raw)return normalise(JSON.parse(raw))}}catch(e){}return clone(DEF)}
function normalise(p){return{settings:{...DEF.settings,...(p.settings||{})},logs:p.logs||{},done:p.done||p.completedTasks||{}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function dateKey(d=new Date()){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function parseDate(s){if(!s)return null;const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d,12)}
function fmtDate(d){return new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'numeric',month:'long'}).format(d)}
function fmtMin(v){const m=Math.max(0,Math.round(Number(v)||0));return`${Math.floor(m/60)}h ${String(m%60).padStart(2,'0')}m`}
function clamp(v,a,b){v=Number(v);return Number.isFinite(v)?Math.min(b,Math.max(a,v)):a}
function round5(v){return Math.max(0,Math.round(v/5)*5)}
function monday(d=new Date()){const x=new Date(d.getFullYear(),d.getMonth(),d.getDate(),12),day=x.getDay();x.setDate(x.getDate()-(day===0?6:day-1));return x}
function daysBetween(a,b){return Math.floor((a-b)/86400000)}
function dayIndex(){const n=new Date();return Math.min(6,Math.max(0,daysBetween(new Date(n.getFullYear(),n.getMonth(),n.getDate(),12),monday())))}
function periodTotal(track,from,to){return Object.entries(state.logs).reduce((n,[k,v])=>{const d=parseDate(k);return(!from||d>=from)&&(!to||d<=to)?n+(Number(v[track])||0):n},0)}
function weekTotal(track){const s=monday(),e=new Date(s);e.setDate(s.getDate()+6);return periodTotal(track,s,e)}
function allTotal(track){return periodTotal(track)}
function expectedWeek(target){return target*((dayIndex()+1)/7)}
function weekPace(track,target){const actual=weekTotal(track);return{actual,diff:actual-expectedWeek(target)}}
function overallPace(){const start=parseDate(state.settings.startDate);if(!start)return null;const now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate(),12),weeks=Math.max(0,(daysBetween(today,start)+1)/7),actual=allTotal('jp')+allTotal('fin'),expected=weeks*(state.settings.jpWeekly+state.settings.finWeekly);return{actual,expected,diff:actual-expected}}
function suggested(track,target,normal){const actual=weekTotal(track),remaining=Math.max(0,target-actual);if(!remaining)return 0;const daysLeft=Math.max(1,7-dayIndex()),needed=remaining/daysLeft,min=track==='jp'?25:40,max=track==='jp'?75:105;return round5(Math.min(remaining,clamp(Math.max(needed,normal*.72),min,max)))}
function id(item,i){return`${item[0]}:${i}`}
function isDone(item,i){return!!state.done[id(item,i)]}
function current(data){for(const item of data)for(let i=0;i<item[6].length;i++)if(!isDone(item,i))return{item,index:i,task:item[6][i]};const item=data[data.length-1];return{item,index:item[6].length-1,task:'All planned milestones complete'}}
function tutorThisWeek(){const s=monday(),e=new Date(s);e.setDate(s.getDate()+6);return Object.entries(state.logs).some(([k,v])=>{const d=parseDate(k);return d>=s&&d<=e&&v.tutor})}
function statusText(diff){if(Math.abs(diff)<=15)return'On pace';return diff>0?`+${fmtMin(diff)} ahead`:`${fmtMin(Math.abs(diff))} behind`}
function overallLabel(){const j=weekPace('jp',state.settings.jpWeekly).diff,f=weekPace('fin',state.settings.finWeekly).diff;if(j>=-20&&f>=-20)return['Mostly on track','good'];if(j<-75||f<-75)return['Needs catch-up','bad'];return['A little behind','warn']}
function jpPlan(){const c=current(JP),mins=suggested('jp',state.settings.jpWeekly,state.settings.jpSession);let title=c.item[2],resource=c.item[3],url=c.item[4],steps=[];if(c.item[0]==='jp-kana'){const low=c.task.toLowerCase(),hira=low.includes('hiragana'),kata=low.includes('katakana');title=hira?'Kana · Hiragana':kata?'Kana · Katakana':'Japanese setup';url=hira?'https://www.tofugu.com/japanese/learn-hiragana/':kata?'https://www.tofugu.com/japanese/learn-katakana/':'https://genki3.japantimes.co.jp/en/student/';resource=hira?'Tofugu · Learn Hiragana':kata?'Tofugu · Learn Katakana':'Genki + Bunpro + tutor setup';steps=[`${c.task} · ${Math.max(15,mins-10)} min`,'Recall from memory · 10 min']}else if(c.item[0]==='jp-g1'||c.item[0]==='jp-g2'){const m=c.task.match(/Lesson (\d+)/),main=Math.max(15,mins-20);title=`${c.item[2]} · ${m?`Lesson ${m[1]}`:'Next lesson'}`;steps=[`${c.task.replace(/^Lesson \d+ · /,'')} · ${main} min`,'Bunpro reviews · 10 min','Minato / easy input · 10 min']}else steps=[`${c.task} · ${Math.max(20,mins-10)} min`,'Bunpro or easy input · 10 min'];return{...c,mins,title,resource,url,steps}}
function finPlan(){const c=current(FIN),x=current(EXCEL),mins=suggested('fin',state.settings.finWeekly,state.settings.finSession),main=Math.max(25,mins-15);return{...c,excel:x,mins,title:c.item[2],resource:c.item[3],url:c.item[4],steps:[`${c.task} · ${main} min`,`Excel: ${x.task} · 15 min`]}}
function todayLog(){return state.logs[dateKey()]||{}}
function renderSteps(el,steps){el.innerHTML='';steps.forEach((s,i)=>{const row=document.createElement('div');row.className='step';row.innerHTML=`<span class="step-num">${i+1}</span><span>${s}</span>`;el.appendChild(row)})}
function quickLink(href,label){return`<a href="${href}" target="_blank" rel="noopener">${label} ↗</a>`}
function setFocus(prefix,p,done,log){const card=document.getElementById(`${prefix}Card`),open=document.getElementById(`${prefix}Open`),btn=document.getElementById(`${prefix}DoneBtn`),quick=document.getElementById(`${prefix}Quick`);open.onclick=null;card.classList.toggle('complete',done);quick.innerHTML=prefix==='jp'?[quickLink('https://bunpro.jp/','Bunpro'),quickLink('https://minato-jf.jp/','Minato'),!tutorThisWeek()?quickLink('https://www.italki.com/','Tutor due this week'):quickLink('https://www.italki.com/','Tutor logged')].join(''):[quickLink('https://www.wallstreetprep.com/self-study-programs/excel-crash-course/','Excel course'),quickLink('https://macabacus.com/features/excel-shortcuts-formatting-financial-modeling','Shortcuts')].join('');if(done){document.getElementById(`${prefix}Suggested`).textContent='Done today';document.getElementById(`${prefix}Title`).textContent=prefix==='jp'?'Japanese complete':'Finance complete';document.getElementById(`${prefix}Resource`).textContent=`Next up: ${p.title} · ${p.resource}`;renderSteps(document.getElementById(`${prefix}Steps`),[`${fmtMin(log[prefix]||0)} logged today`,'Come back tomorrow, or add extra time from Log.']);if(p.url){open.href=p.url;open.textContent='Preview next resource ↗'}else{open.href='#';open.textContent='Open plan';open.onclick=e=>{e.preventDefault();switchView('plan')}}btn.disabled=true;btn.textContent='Done';return}document.getElementById(`${prefix}Suggested`).textContent=p.mins?`${p.mins} min`:'Target met';document.getElementById(`${prefix}Title`).textContent=p.mins?p.title:'Weekly target complete';document.getElementById(`${prefix}Resource`).textContent=p.mins?p.resource:'Optional review only';renderSteps(document.getElementById(`${prefix}Steps`),p.mins?p.steps:['No scheduled study needed unless you want extra review.']);if(p.url&&p.mins){open.href=p.url;open.textContent='Open resource ↗'}else if(!p.mins){open.removeAttribute('href');open.textContent='Weekly target met'}else{open.href='#';open.textContent='Open plan';open.onclick=e=>{e.preventDefault();switchView('plan')}}btn.disabled=!p.mins;btn.textContent='Done & advance'}
function setPace(prefix,p,target){document.getElementById(`${prefix}WeekText`).textContent=`${fmtMin(p.actual)} / ${fmtMin(target)}`;document.getElementById(`${prefix}Bar`).style.width=`${Math.min(100,p.actual/target*100)}%`;document.getElementById(`${prefix}Delta`).textContent=statusText(p.diff)+(p.diff<0?' · today’s session adapts to catch up':'')}
function renderToday(){const now=new Date();document.getElementById('headerDate').textContent=fmtDate(now);document.getElementById('pageTitle').textContent='Today';document.getElementById('setupBanner').classList.toggle('hidden',!!state.settings.startDate);const start=parseDate(state.settings.startDate);document.getElementById('weekNo').textContent=start?`Plan week ${Math.max(1,Math.floor(daysBetween(new Date(),start)/7)+1)}`:'';const jp=jpPlan(),fin=finPlan(),log=todayLog(),jOpen=jp.mins>0&&!log.jpDone,fOpen=fin.mins>0&&!log.finDone,blocks=[jOpen,fOpen].filter(Boolean).length,total=(jOpen?jp.mins:0)+(fOpen?fin.mins:0);document.getElementById('todaySummary').textContent=blocks?`${blocks} study block${blocks===1?'':'s'} · ${fmtMin(total)}`:(log.jpDone||log.finDone?'Today’s plan complete':'Weekly targets met');setFocus('jp',jp,!!log.jpDone,log);setFocus('fin',fin,!!log.finDone,log);const j=weekPace('jp',state.settings.jpWeekly),f=weekPace('fin',state.settings.finWeekly);setPace('jp',j,state.settings.jpWeekly);setPace('fin',f,state.settings.finWeekly);const o=overallLabel(),status=document.getElementById('overallStatus');status.textContent=o[0];status.className=`status ${o[1]}`;const all=overallPace();document.getElementById('overallDelta').textContent=all?`${all.diff>=0?'+':'−'}${fmtMin(Math.abs(all.diff))} vs plan`:'Set a start date'}
function completeSession(track){const plan=track==='jp'?jpPlan():finPlan();if(!plan.mins)return;const k=dateKey(),log=state.logs[k]||{};log[track]=Math.max(Number(log[track])||0,plan.mins);log[`${track}Done`]=true;state.logs[k]=log;state.done[id(plan.item,plan.index)]=true;if(track==='fin'&&plan.excel)state.done[id(plan.excel.item,plan.excel.index)]=true;save();renderAll()}
function renderRoad(data,targetId){const host=document.getElementById(targetId);host.innerHTML='';const cur=current(data);data.forEach(item=>{const total=item[6].length,done=item[6].filter((_,i)=>isDone(item,i)).length,isCurrent=item[0]===cur.item[0],details=document.createElement('details');details.className='road-item';details.open=isCurrent;details.innerHTML=`<summary><div class="road-main"><div class="phase">${item[1]}</div><div class="road-title">${item[2]}</div><div class="road-resource">${item[3]}</div></div><span class="current-tag ${isCurrent?'now':''}">${isCurrent?'Now':done===total?'Done':`${done}/${total}`}</span></summary><div class="road-body"><p class="road-note">${item[5]}</p>${item[4]?`<a class="resource-link" href="${item[4]}" target="_blank" rel="noopener">Open resource ↗</a>`:''}<div class="task-list"></div></div>`;const list=details.querySelector('.task-list');item[6].forEach((t,i)=>{const label=document.createElement('label');label.className=`task ${isDone(item,i)?'done':''}`;label.innerHTML=`<input type="checkbox" ${isDone(item,i)?'checked':''}><span>${t}</span>`;label.querySelector('input').addEventListener('change',e=>{const k=id(item,i);if(e.target.checked)state.done[k]=true;else delete state.done[k];save();renderAll()});list.appendChild(label)});host.appendChild(details)})}
function renderLibrary(){const el=document.getElementById('resourceLibrary');el.innerHTML='';RES.forEach(r=>{const row=document.createElement('div');row.className='resource-row';row.innerHTML=`<div><h3>${r[0]}</h3><p>${r[1]}</p><a class="resource-link" href="${r[3]}" target="_blank" rel="noopener">Open ↗</a></div><span class="cost">${r[2]}</span>`;el.appendChild(row)})}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function renderLog(){document.getElementById('logDateTitle').textContent=fmtDate(new Date());const l=todayLog();document.getElementById('jpMins').value=l.jp??'';document.getElementById('finMins').value=l.fin??'';document.getElementById('jpDone').checked=!!l.jpDone;document.getElementById('finDone').checked=!!l.finDone;document.getElementById('tutorDone').checked=!!l.tutor;document.getElementById('note').value=l.note||'';const hist=document.getElementById('historyList'),entries=Object.entries(state.logs).sort((a,b)=>b[0].localeCompare(a[0]));hist.innerHTML='';if(!entries.length){hist.innerHTML='<div class="empty">No check-ins yet.</div>';return}entries.slice(0,60).forEach(([k,v])=>{const row=document.createElement('div');row.className='history-row';row.innerHTML=`<div class="history-date">${fmtDate(parseDate(k))}</div><div><strong>JP</strong> ${fmtMin(v.jp||0)} · <strong>Finance</strong> ${fmtMin(v.fin||0)}${v.tutor?' · Tutor ✓':''}${v.note?`<div class="history-note">${escapeHtml(v.note)}</div>`:''}</div>`;hist.appendChild(row)})}
function renderSettings(){document.getElementById('startDate').value=state.settings.startDate||dateKey();document.getElementById('jpWeekly').value=state.settings.jpWeekly;document.getElementById('finWeekly').value=state.settings.finWeekly;document.getElementById('jpSession').value=state.settings.jpSession;document.getElementById('finSession').value=state.settings.finSession}
function renderAll(){renderToday();renderRoad(JP,'jpRoad');renderRoad(FIN,'finRoad');renderRoad(EXCEL,'excelRoad');renderLibrary();renderLog();renderSettings()}
function switchView(name){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(`${name}View`).classList.add('active');document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===name));document.getElementById('pageTitle').textContent=name==='today'?'Today':name==='plan'?'Plan':'Log';window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.nav-btn').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));document.getElementById('jpDoneBtn').addEventListener('click',()=>completeSession('jp'));document.getElementById('finDoneBtn').addEventListener('click',()=>completeSession('fin'));
document.getElementById('logForm').addEventListener('submit',e=>{e.preventDefault();const k=dateKey(),prev=state.logs[k]||{};state.logs[k]={...prev,jp:clamp(document.getElementById('jpMins').value||0,0,600),fin:clamp(document.getElementById('finMins').value||0,0,600),jpDone:document.getElementById('jpDone').checked,finDone:document.getElementById('finDone').checked,tutor:document.getElementById('tutorDone').checked,note:document.getElementById('note').value.trim()};save();renderAll();const m=document.getElementById('saved');m.textContent='Saved.';setTimeout(()=>m.textContent='',1600)});
const dlg=document.getElementById('settingsDialog');function openSettings(){renderSettings();dlg.showModal()}document.getElementById('settingsBtn').addEventListener('click',openSettings);document.getElementById('setupBtn').addEventListener('click',openSettings);document.getElementById('closeSettings').addEventListener('click',()=>dlg.close());document.getElementById('saveSettings').addEventListener('click',()=>{state.settings.startDate=document.getElementById('startDate').value||dateKey();state.settings.jpWeekly=clamp(document.getElementById('jpWeekly').value,30,1200);state.settings.finWeekly=clamp(document.getElementById('finWeekly').value,30,1200);state.settings.jpSession=clamp(document.getElementById('jpSession').value,15,120);state.settings.finSession=clamp(document.getElementById('finSession').value,20,180);save();dlg.close();renderAll()});
document.getElementById('exportBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`learning-roadmap-${dateKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),500)});document.getElementById('importInput').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{const p=JSON.parse(await file.text());state=normalise(p);save();renderAll();alert('Backup imported.')}catch(err){alert('That is not a valid Learning Roadmap backup.')}e.target.value=''});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));renderAll();