const genkiTasks=(start,end)=>{const out=[];for(let n=start;n<=end;n++){out.push(`Lesson ${n} · dialogue + vocabulary`);out.push(`Lesson ${n} · grammar + workbook / listening`)}return out};
const JP=[
['jp-kana','Start','Kana + setup','Tofugu + Genki setup','https://www.tofugu.com/japanese/learn-hiragana/','Clear kana quickly, then stop using romaji.',['Learn hiragana','Hiragana recall drill from memory','Learn katakana','Katakana recall drill from memory','Set up Genki I + workbook + Bunpro + recurring tutor']],
['jp-g1','Foundation','Genki I','Genki I + workbook','https://genki3.japantimes.co.jp/en/student/','Your main beginner syllabus. Say exercises aloud rather than only reading explanations.',genkiTasks(1,12)],
['jp-g2','Foundation','Genki II','Genki II + workbook','https://genki3.japantimes.co.jp/en/student/','Move toward a functional N4 base while maintaining speaking and input.',genkiTasks(13,23)],
['jp-n3','Pre-Japan bridge','N4 → early N3','Genki complete + Bunpro + graded/native input','https://minato-jf.jp/','Bridge into N3 material before intensive study in Japan.',['Consolidate weak Genki grammar','Begin N3 grammar / vocabulary','Read an easy graded story comfortably','Hold a 15-minute unscripted conversation','Begin easy native material with lookups']]
];
const FIN=[
['fa','Phase 1','Financial accounting','Wharton · Introduction to Financial Accounting','https://www.coursera.org/learn/wharton-accounting','Learn to read and connect the income statement, balance sheet and cash-flow statement.',['Module 1 · reporting + balance sheet','Module 2 · accrual accounting + income statement','Module 3 · cash-flow statement','Module 4 · ratio analysis + final assessment','Build a simple three-statement practice model','Explain depreciation, working capital and cash flow without notes']],
['fund','Phase 2','Finance fundamentals','Wharton · Fundamentals of Finance','https://www.coursera.org/learn/finance-fundamentals','Build the maths and intuition behind investment decisions.',['Modules 1–2 · NPV / interest / valuation','Modules 3–4 · returns / risk / capital budgeting','Optional capital structure + leverage material','Finish course assessment','Explain NPV, IRR and gearing in plain English']],
['corp','Phase 3','Corporate finance','Wharton · Introduction to Corporate Finance','https://www.coursera.org/learn/wharton-finance','Reinforce cash-flow forecasting, DCF and return-on-investment decisions.',['Week 1 · time value of money','Week 2 · interest rates + DCF','Week 3 · free cash flow + forecasting','Week 4 · ROI + sensitivity analysis','Rebuild a simple DCF from blank']],
['fa2','Phase 4','Deeper financial accounting','Wharton · More Introduction to Financial Accounting','https://www.coursera.org/learn/wharton-financial-accounting/','Deepen the accounting areas that matter when reading models, accounts and diligence materials.',['Modules 1–2','Modules 3–4','Modules 5–6','Finish course assessment','Review one real annual report using the course framework']],
['swan','Phase 5','Renewable project finance','Swansea · Introduction to Project Finance for Renewable Energy','https://switchonskills.swansea.ac.uk/introduction-to-project-finance-for-renewable-energy/','Bridge finance theory into renewable project finance and spreadsheet work.',['SPV / limited-recourse structure','Renewable revenues + costs','Debt / equity + cash-flow block','Spreadsheet exercise 1','Spreadsheet exercise 2','Explain CFADS / bankability / project vs equity returns']],
['grid','Phase 6','Professional modelling','Gridlines · Essential Financial Modelling','https://academy.gridlines.com/p/essential-financial-modelling-ipfa','Learn clean, auditable infrastructure-model architecture.',['Model architecture + timeline','Revenue + opex','Three-statement linking','Debt + equity','Checks + sensitivities','Rebuild one section without following the instructor']],
['cpfm','Phase 7','Advanced project finance','PFI · Certificate in Project Finance Modelling','https://www.projectfinanceinstitute.com/certificate-in-project-finance-modelling','Learn the debt and returns machinery underneath infrastructure investing.',['Sources & uses + construction financing','CFADS build','Debt sizing + sculpting','DSCR / LLCR / PLCR','DSRA + shareholder loans + waterfall','Mini-perms / refinancing / hedging','Rebuild a simplified PF debt section from blank']],
['bodmer','Phase 8','Renewables specialisation','Edward Bodmer · renewable + battery exercises','https://edbodmer.com/exercises-for-renewable-energy-course/','Hands-on wind, P50/P90, debt sizing and battery practice.',['Wind / resource / P50-P90 exercise','Renewable debt-sizing exercise','Battery efficiency / degradation exercise','Merchant-price / battery economics exercise']],
['ofsw','Capstone','Offshore-wind investment model','Your own fictional/public-data workbook','','Build a simple model from blank to prove you understand the full economic chain.',['Gross → net AEP loss stack','CfD / PPA / merchant revenue','Opex + CFADS','Construction capex + debt draws','P50/P90 + debt sizing / DSCR','Project IRR + equity IRR + sensitivities']],
['bess','Capstone','UK BESS investment model','Your own fictional/public-data workbook','','Connect battery assumptions through the revenue stack, financing and returns.',['MW / MWh / duration / availability','RTE / cycles / degradation / augmentation','CM + merchant + ancillary revenue + optimiser fee','EBITDA → CFADS','Debt sizing + DSCR','Project / equity returns + sensitivities']]
];
const EXCEL=[
['excel','Parallel','Excel keyboard fluency','Wall Street Prep · Excel Crash Course','https://www.wallstreetprep.com/self-study-programs/excel-crash-course/','Learn shortcuts inside real modelling work.',['Navigation + selection','F2 / F4 / fill / paste special','Formatting + number formats','Formula tracing / auditing','Data tables + sensitivities','Keyboard-first 60-minute modelling session']],
['excel-ref','Reference','Shortcut reference','Macabacus + ExcelJet','https://macabacus.com/features/excel-shortcuts-formatting-financial-modeling','Reference only. Look things up when a repeated mouse action annoys you.',['Build personal top-20 shortcut list','Add 10 advanced shortcuts you genuinely use']]
];
const RES=[
['Genki I + II','Core Japanese syllabus','Paid books','https://genki3.japantimes.co.jp/en/student/'],['Bunpro','Grammar + vocabulary spaced review','~$5/mo','https://bunpro.jp/'],['1-on-1 tutor','Corrected speaking','Variable','https://www.italki.com/'],['Japan Foundation Minato','Level-appropriate input','Mostly free','https://minato-jf.jp/'],['Wharton · Intro Financial Accounting','Financial-statement foundation','Coursera','https://www.coursera.org/learn/wharton-accounting'],['Wharton · Fundamentals of Finance','NPV, IRR, valuation and leverage','Coursera','https://www.coursera.org/learn/finance-fundamentals'],['Wharton · Intro Corporate Finance','DCF, FCF, forecasting and ROI','Coursera','https://www.coursera.org/learn/wharton-finance'],['Wharton · More Financial Accounting','Deeper accounting','Coursera','https://www.coursera.org/learn/wharton-financial-accounting/'],['OpenTuition ACCA FA','Optional accounting fallback','Free','https://opentuition.com/acca/'],['Swansea Renewable Project Finance','Renewable PF bridge','Free','https://switchonskills.swansea.ac.uk/introduction-to-project-finance-for-renewable-energy/'],['Gridlines Essential Financial Modelling','Infrastructure modelling discipline','Free','https://academy.gridlines.com/p/essential-financial-modelling-ipfa'],['PFI CPFM','Advanced PF modelling','~$60/mo','https://www.projectfinanceinstitute.com/certificate-in-project-finance-modelling'],['Edward Bodmer exercises','Wind / P50-P90 / debt / BESS','Free','https://edbodmer.com/exercises-for-renewable-energy-course/'],['WSP Excel Crash Course','Finance-style Excel speed','~$39 once','https://www.wallstreetprep.com/self-study-programs/excel-crash-course/'],['Macabacus','Excel shortcut reference','Free','https://macabacus.com/features/excel-shortcuts-formatting-financial-modeling'],['ExcelJet','Formula / shortcut lookup','Free','https://exceljet.net/']
];